### ISSUE TITLE
Simplify function calls in Testing

### ISSUE THREAD

**Issue by NouDaimon** [solidstate-network/solidstate-solidity#108]
Given the new spec rework, it makes more sense to use the simplified version function calling in tests, as opposed to the function calls with the full signature, meaning:

`await someContract.someFunction(someParam);`

as opposed to:

`await someContract['someFunction(uint256)'](someParam);`

The reason is that the new spec handles all overloading cases except the case where overloaded functions are defined in the same interface.

**Comment by ItsNickBarry** [comment]
@NouDaimon I was mistaken about the reasons that this might be desirable.  We must in fact do the opposite.
