### ISSUE TITLE
False pass ERC1155Base reverts if burn amount exceeds balance

### ISSUE THREAD

**Issue by ElmoArmy** [solidstate-network/solidstate-solidity#124]
The following line contains an error.
https://github.com/solidstate-network/solidstate-solidity/blob/52c913b1e68ee5483c923690c83e611532200e37/test/token/ERC1155/ERC1155Base.ts#L310-L315

according to the contract
https://github.com/solidstate-network/solidstate-solidity/blob/52c913b1e68ee5483c923690c83e611532200e37/contracts/token/ERC1155/base/ERC1155BaseInternal.sol#L184-L187

the expected error reason should therefore be plural, ie.:
```ERC1155: burn amount exceeds balances```

---
### As to why this bug exists yet the test passes 
The ethereum-waffle chai assertion for revertedWith checks for the expected string to be anywhere in the error string. So expecting a blank space, or ```ERC```, or any other substring of the actual error would also pass this assertion and since the substring up to balance is the same, we observe this false match. 

 I'd recommend ( and so does hardhat 😆) migrating to hardhat's own [hardhat-chai-matchers](https://hardhat.org/hardhat-chai-matchers/docs/overview) which has a less footgunny exact match for this assertion.

**Comment by ItsNickBarry** [comment]
Fixed.  Will be included in next release.  I'll consider switching to that alternative plugin soon.
