### ISSUE TITLE
Organize data structures

### ISSUE THREAD

**Issue by ItsNickBarry** [solidstate-network/solidstate-solidity#128]
As we add more data structure libraries, it makes sense to standardize their interfaces and how they're published.  This will affect the scope of #126 and #127.

Data structures should all be stored in the `contracts/data/` directory.

It seems like each data structure should have an implementation for each of `address`, `uint256`, and `bytes32`.  What do you think, @0xCourtney?

**Comment by ItsNickBarry** [comment]
Also related: #34, #69.

**Comment by 0xCourtney** [comment]
These data structures can accommodate the three types suggested above. The AVL tree structure has an `Index` struct which stores data about the tree such as the root node id, length, and mapping of nodes. The `Node` struct stores node metadata (parent, left, right indexes, node height), the id, and arbitrary values. I propose having three different `Node` types. `AddressNode`, `UintNode`, and `Bytes32Node` similar to what has been done in the `EnumerableSet` library.

```solidity
struct Index {
   bytes32 head;
   bytes32 length;
   bytes32 root;
   mapping (bytes32 => Node) nodes;
}

struct Node {
   bytes32 id;
   bytes32 value;
   bytes32 parent;
   bytes32 left;
   bytes32 right;
   bytes32 height;
}

struct Bytes32Node {
   Index _index;
}

struct AddressNode {
   Index _index;
}

struct UintNode {
   Index _index;
}
```

**Comment by ItsNickBarry** [comment]
Okay, let's repeat that pattern then.  Best to branch off of `data-structures` branch for each new data structure (for now).
