### ISSUE TITLE
incorrect implementation of Diamond

### ISSUE THREAD

**Issue by wiasliaw** [solidstate-network/solidstate-solidity#141]
Diamond contract is a proxy of lookup table of addresses and function selectors. Some of the functions are specified in EIP, but they can be removed. However, current implementation inherit the `DiamondReadable` and `DiamondWriteable`, which cause function shadowing and make them unable to be removed. Otherwise, calling these functions doesn't use delegate call (due to function shadowing).

---

From [eip2535 substack](https://eip2535diamonds.substack.com/p/useful-data-for-eip-2535-diamonds), there is a term called Finished Diamond.
> Finished Diamond: A finished diamond was an upgradeable diamond and had a number of upgrades. Then its diamondCut function and/or other upgrade functions were removed and upgrades are no longer possible. It is no longer possible to add/replace/remove functions. It has become an immutable diamond.

**Comment by ItsNickBarry** [comment]
The `SolidStateDiamond` contract is the "recommended" configuration for most users.  In my opinion, the need for a "finished diamond" is very rare, so `SolidStateDiamond` does not support that feature.  However, it is still a valid diamond implementation - all functions inherited into the proxy are properly registered as "immutable functions".

A user who wishes to implement a "finished diamond" can do so manually by using `DiamondBase` as the proxy, and `DiamondWritable` as a facet.

I will consider adding another full implementation that can be a "finished diamond", but at the moment I still don't think it's necessary.
