### ISSUE TITLE
cant find the IERC173.sol

### ISSUE THREAD

**Issue by furkandemireleng** [solidstate-network/solidstate-solidity#149]
```
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.8;

import "@solidstate/contracts/proxy/diamond/SolidStateDiamond.sol";

contract PDiamond is SolidStateDiamond{}
```

the basic contract for diamond proxy example

`
Error: not found @solidstate/contracts/access/IERC173.sol`

I am getting this compiler error and idk why ? Can you help me please  🙏

**Comment by ItsNickBarry** [comment]
Standard interfaces defined in EIPs have been moved to the `contracts/interfaces/` directory.  Apologies for the breaking change - the API should be more stable once we release version `1.0.0`.

However, I'm not sure why you're getting that error when importing `SolidStateDiamond`.  Internal references have been updated.  Try forcing a reinstall of your dependencies.

**Comment by furkandemireleng** [comment]
I am using with remix. Can you please write me for proper import ? Thanks again for your quick responses and detail examples. I am newbie for the diamond and your solidstate thats why I am asking again for detail import example 

Thanks 🙏 😊

**Comment by ItsNickBarry** [comment]
The import is `import { IERC173 } from '@solidstate/contracts/interfaces/IERC173.sol';`

In m experience, Remix is good for quick testing and for its front-end dapp interface, but not ideal for development.  I haven't used it in several years, so I can't offer support if you encounter further issues with it.  I recommend that you set up a development environment with Hardhat and either NPM or yarn.

**Comment by furkandemireleng** [comment]
okay thank you for your comments
