### ISSUE TITLE
solidstate Diamond implementation examples

### ISSUE THREAD

**Issue by makinghappen** [solidstate-network/solidstate-solidity#156]
Hi, I am considering switching to solidstate Diamond implementation from the original reference implementation(diamond-1-hardhat), maybe there is a usage example?

**Comment by ItsNickBarry** [comment]
Simply import and inherit `SolidStateDiamond` into your own contract.

```solidity
import { SolidStateDiamond } from '@solidstate/contracts/proxy/diamond/SolidStateDiamond.sol';

contract MyDiamond is SolidStateDiamond {}
```

For a comprehensive example, see the [Premia contracts](https://github.com/Premian-Labs/premia-contracts).

**Comment by makinghappen** [comment]
@ItsNickBarry thanks!
Maybe you also have examples how to import your ERC1155 contract implementation to be used from a Facet and from a Library?

**Comment by ItsNickBarry** [comment]
The Premia contracts linked above include ERC1155.  It's a rather complicated example, however.  I hope to have some simpler examples soon, but for now I can only point to Premia.
