### ISSUE TITLE
Virtual attribute removed

### ISSUE THREAD

**Issue by julesGoullee** [solidstate-network/solidstate-solidity#16]
Didn't get why the `virtual` modifier has been removed compared to openzepplin version. For example for mint and burn it's a common pattern to overwrite this function, why the choice?

**Comment by ItsNickBarry** [comment]
I'll accept a PR to add `virtual` anywhere it's needed.

**Comment by julesGoullee** [comment]
Allright see. #17

**Comment by ItsNickBarry** [comment]
Released in version `0.0.12`.  Thanks for the PR.
