### ISSUE TITLE
Functions in ERC721Base.sol not marked as virtual

### ISSUE THREAD

**Issue by JuanCarlos-Spaceport** [solidstate-network/solidstate-solidity#174]
Hey,

I was going trough the implementation of `ERC721` and noticed a little incoherence on the functions `approve`, `setApprovalForAll` and `isApprovedForAll`.

On other token implementations like `ERC1155` or `ERC20` those functions are marked as `virtual`, is this an intended implementation? If so, would't it make more sense to keep those functions as in the ERC721 definition?

**Comment by ItsNickBarry** [comment]
Which file exactly?  Yes, there are some inconsistencies, especially in the case of ERC721 because I rarely use that standard.  Some of these inconsistencies may have been fixed or partially fixed in #171.

**Comment by JuanCarlos-Spaceport** [comment]
So far only noticed the inconsistencies on [ERC721Base.sol](https://github.com/solidstate-network/solidstate-solidity/blob/master/contracts/token/ERC721/base/ERC721Base.sol) `approve`, `isApprovedForAll ` and `setApprovalForAll ` should be marked as virtual.

This is not fixed in https://github.com/solidstate-network/solidstate-solidity/pull/171 but if you want to i can create a PR with the changes that should be made :)

**Comment by ItsNickBarry** [comment]
See [ERC721BaseInternal](https://github.com/solidstate-network/solidstate-solidity/blob/master/contracts/token/ERC721/base/ERC721BaseInternal.sol).  In SolidState, `internal` functions should always be marked `virtual`, while `external` functions should _never_ be marked `virtual`.  If you need to override behavior, override the `internal` function.
