### ISSUE TITLE
Non-`Enumerable` ERC1155 and ERC721?

### ISSUE THREAD

**Issue by RogerPodacter** [solidstate-network/solidstate-solidity#190]
I notice that both `SolidStateERC721` and `SolidStateERC1155` are `Enumerable`. Given this costs extra gas and I don't need on-chain enumeration for my project, I was trying to find an non-enumerable version but I couldn't.

Is there a way to do this with the current library?

If not, I'd propose it as an addition, with the non-enumerable version as the default. IMO non-enumerable is correct for most use-cases and it is also the default in the OpenZeppelin contracts.

Thanks!

**Comment by ItsNickBarry** [comment]
See `ERC721Base` and `ERC1155Base`.  Enumerable is the "recommended" configuration here because SS focuses on upgradeable contracts.  It's difficult to add enumeration via upgrade because it depends on keeping storage mappings up-to-date.

**Comment by RogerPodacter** [comment]
> See `ERC721Base` and `ERC1155Base`

The base contracts don't have the Enumerable interface, but they still pay the cost of this functionality because `ERC721BaseStorage` uses enumerable data structures for `tokenOwners` and `holderTokens`. Is there any way to avoid paying this cost?

I understand your reasoning, but at the same time enumerability is quite expensive and almost never needed (in my opinion). Also I'd add that it's difficult to *remove* enumeration via upgrade because there are no diamond-compatible ERC721 base contracts that don't implement it haha.

Anyway I'm loving solidstate overall!
