### ISSUE TITLE
Declare ERC165Base supportsInterface() as virtual

### ISSUE THREAD

**Issue by opixelum** [solidstate-network/solidstate-solidity#194]
In order to have an **ERC721 diamond**, we need to **override** `supportsInterface` function, defined in the **ERC165Base** contract. However, this function is **not declared** as `virtual`, the **required** keyword for **functions that needs to be overridden**.

**Comment by ItsNickBarry** [comment]
The `ERC165BaseInternal` functions have been marked as `virtual` in c66ab79bca1196782ac7c961ab7a443869915489.  Published in `0.0.53`  You can override those if necessary.

**Comment by opixelum** [comment]
Alright thank you for your help.
