### ISSUE TITLE
Help with Flattening Files

### ISSUE THREAD

**Issue by jewelsonn** [solidstate-network/solidstate-solidity#208]
I have a simple ERC721 Contract and 
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;
import "@solidstate/contracts/token/ERC721/SolidStateERC721.sol";

contract SampleERC721 is SolidStateERC721 {
  //Contract data.....
}
```
The contract compiles properly except when I try to Flatten it I get this error. 

Error: **There is a cycle in the dependency graph, can't compute topological ordering.**

I don't understand the error. I know there is a loop that causes it to trigger as a parent is also acting like a child or something like that. 

Can you tell me how to I flatten it?

**Comment by ItsNickBarry** [comment]
Fixed in latest release.
