### ISSUE TITLE
resolve TODO in DiamondFallback.sol

### ISSUE THREAD

**Issue by vsmelov** [solidstate-network/solidstate-solidity#213]
it's not clear why TODO is placed there
https://github.com/solidstate-network/solidstate-solidity/blob/master/contracts/proxy/diamond/fallback/DiamondFallback.sol#L10
there is an import of IDiamondFallback, isn't it enough?

maybe just remove the line, it's confusing, it looks like the contract is not coomplete

**Comment by ItsNickBarry** [comment]
Fixed in 7be27707a219634aeb07aafeac9f85e301138e53.
