### ISSUE TITLE
include documentation how to operate with Diamonds to README.md

### ISSUE THREAD

**Issue by vsmelov** [solidstate-network/solidstate-solidity#214]
It's not clear how I can quickly start using your Diamond-pattern contracts.
I have already spent 1 hour trying to understand how all this work under the hood and how to rewrite my existing contract in your style.
 
Adding some explanations and examples to README.md would be extremely helpful :-)

Thank you for your big work with EIP-2535 :-)

**Comment by ItsNickBarry** [comment]
Some articles are being planned.  It's been mentioned in the discord server, but there's not much information to report at the moment.  No ETA, but hopefully soon.
