### ISSUE TITLE
AccessControlEnumerable?

### ISSUE THREAD

**Issue by tess3rac7** [solidstate-network/solidstate-solidity#215]
Apologies if there is an existing issue for this (couldn't find any using keyword searches), but are there any plans to add the enumerable version of AccessControl?

Edit: I see that `AccessControl` internally uses `EnumerableSet` so we just need to expose the length functions. If that would be an acceptable addition to the existing `AccessControl` contract I would be happy to make a PR for it.

**Comment by ItsNickBarry** [comment]
A PR would be welcome.

**Comment by tess3rac7** [comment]
Added https://github.com/solidstate-network/solidstate-solidity/pull/216 :slightly_smiling_face:
