### ISSUE TITLE
Which diamond version is used?

### ISSUE THREAD

**Issue by opixelum** [solidstate-network/solidstate-solidity#217]
I have a question about your implementation of the diamond pattern.

Which Nick Mudge's diamond implementation do you use for yours (1, 2 or 3)?

See [https://github.com/mudgen/diamond](https://t.co/yqTElqMbA0).

**Comment by ItsNickBarry** [comment]
Based on reference diamond number 2.

**Comment by opixelum** [comment]
Thank you!
