### ISSUE TITLE
I can't use ERC1155Buyer and ERC1155Holders contracts

### ISSUE THREAD

**Issue by kursadcs** [solidstate-network/solidstate-solidity#223]
hi, 
when I call ERC1155 Holders and Receiver contracts I get error in console. 
What do I need to do for my contract to accept the ERC1155 token? 

**When I used Mudgen diamond I got successful results when I used ERC1155Holders.sol**

**Comment by ItsNickBarry** [comment]
Third party contracts cannot be explicitly supported here.  There is an open issue to add support for ERC1155 receivers - see #98.
