### ISSUE TITLE
Add Safecast library 

### ISSUE THREAD

**Issue by Lumyo** [solidstate-network/solidstate-solidity#30]

**Comment by ItsNickBarry** [comment]
What is Safecast?  Is there an existing implementation elsewhere for reference?

**Comment by Lumyo** [comment]
@ItsNickBarry Thats to protect from overflow on downcasting (Solidity v0.8 still doesnt protect from that)

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/math/SafeCast.sol

**Comment by ItsNickBarry** [comment]
Added in commit 0a0a8899ea63f78e97d86da9c000e081c87bc51f.
