### ISSUE TITLE
Request: Add support for a general role based access control mechanism

### ISSUE THREAD

**Issue by amartinezuy** [solidstate-network/solidstate-solidity#63]
Currently, SolidState provide access control through the `Ownable` contract.

This is enough for many applications. But some advanced use cases would benefit from a customizable mechanism for role based access control.

The [Access Control implementation by OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/access) may serve as an inspiration for implementing a similar a mechanism in SolidState.

**Comment by friskyfoxdk** [comment]
Would love to see this implemented as well

**Comment by ItsNickBarry** [comment]
I will try to prioritize this a bit more, though it will still take some time.  Would accept a PR in the meantime.

**Comment by friskyfoxdk** [comment]
I'll take a swing at it this week 👍

**Comment by iam-dev** [comment]
[iam-dev:feature/AccessControl-#63](https://github.com/solidstate-network/solidstate-solidity/pull/95)

still need testing thou

**Comment by ItsNickBarry** [comment]
Implemented in #95 and released in version `0.0.42`.  Thanks @iam-dev.
