### ISSUE TITLE
Add documentation on how to install solidstate

### ISSUE THREAD

**Issue by mudgen** [solidstate-network/solidstate-solidity#79]
Perhaps add to the readme how to install solidstate npm package so it can be used in contracts.

**Comment by ItsNickBarry** [comment]
It's already in the `@solidstate/contracts` readme.  You think it should be in the main readme too?

**Comment by mudgen** [comment]
oh you are right, I didn't see that. cool.     Yea, if you think it is a good idea.

**Comment by ItsNickBarry** [comment]
I plant to write an integration guide which describes the SolidState inheritance patterns, and which contracts users should import in which circumstances.  I'll use that as opportunity to make installation and setup very clear.
