### ISSUE TITLE
Suggest removing `diamondCut` as an immutable function

### ISSUE THREAD

**Issue by mudgen** [solidstate-network/solidstate-solidity#85]
From the EIP2535 Diamonds standard an immutable function is a function defined directly in a diamond so it can never be removed.

In solidstate-solidity the `diamondCut` function is defined as an immutable function in the Diamond.sol implementation: https://github.com/solidstate-network/solidstate-solidity/blob/master/contracts/proxy/diamond/Diamond.sol

But one of the features of a diamond is the ability to remove the `diamondCut` function at some point to make an immutable diamond.  It would be useful if the `diamondCut` function was added to a diamond, but not as an immutable function so diamond owners have the ability to remove it or replace it.

**Comment by ItsNickBarry** [comment]
`Diamond.sol` is the "SolidState recommended implementation" of a diamond proxy.  Most users will likely never want to remove the `diamondCut` function, so it is marked as immutable here.  Users who do plan to "finalize" a diamond at some point can use `DiamondBase.sol` to set up their own diamonds, and add a contract derived from `DiamondCuttable.sol` as a non-immutable facet.

I intend to describe the difference between base components and "SolidState recommended" contracts in a future documentation update.  As an example, `ERC20.sol` works the same way - it is an "opinionated" contract in that it includes additional approval and metadata functions which are not part of the ERC20 standard but are desirable in most cases.
