### ISSUE TITLE
Override Interfaces issue when compiling

### ISSUE THREAD

**Issue by nohehf** [solidstate-network/solidstate-solidity#89]
I can't compile my project when I use any solidstate-solidity, I get the following error multiple times (for every contract / interface that is used):
```
TypeError: Overriding function is missing "override" specifier.
  --> @solidstate/contracts/introspection/ERC165.sol:17:5:
   |
17 |     function supportsInterface(bytes4 interfaceId) public view returns (bool) {
   |     ^ (Relevant source part starts here and spans across multiple lines).
Note: Overridden function is here:
  --> @solidstate/contracts/introspection/IERC165.sol:15:5:
   |
15 |     function supportsInterface(bytes4 interfaceId) external view returns (bool);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

...
SAME KIND OF ISSUE DOZENS OF TIMES
...
```

The file that is currently causing the issue is:
```SOLIDITY
// SPDX-License-Identifier: UNLICENCED
pragma solidity ^0.8.0;

import "@solidstate/contracts/token/ERC1155/ERC1155.sol";

contract ERC1155Facet is ERC1155 {
    // ...
}
```
But inheriting from any contract would give the same issue.

## My config:
Solidity Remote compiler: latest
Hardhat config:
```
solidity: '0.8.6',
  settings: {
    optimizer: {
      enabled: true,
      runs: 200
    }
  }
```
"@solidstate/contracts": "^0.0.31"

**Comment by ItsNickBarry** [comment]
Solidity version must be at least `0.8.8` for some files.  See #67.  Arguably we should specify these requirements in the pragma statement of each file, but until a SolidState `1.0.0` release this level of precision is unnecessary overhead.

**Comment by nohehf** [comment]
I fixed the issue by upgrading hardhat solidity version to 0.8.9, as I discovered in #67 .
Tho I think it would be interesting to mention this in the docs.
I can open a PR for this if you find that this is relevant.

Not related to this issue but I think that it would be really cool to have some docs for this hole library too, and I'll be glad to. help.

**Comment by nohehf** [comment]
> Solidity version must be at least `0.8.8` for some files. See #67. Arguably we should specify these requirements in the pragma statement of each file, but until a SolidState `1.0.0` release this level of precision is unnecessary overhead.

I was writing hah, but yep I figured this out, thx and sorry for disturbing.
